# Server
server.port=8080

# MySQL Database Connection (Railway)
spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:14939/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sBsPFSRloJcxfoAaVRJTjXMxcSRyxrYe

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional (avoid warning)
spring.jpa.open-in-view=false